# This is a basic workflow to help you get started with Actions

name: Assemble 19200 Baud demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths-ignore:
      - 'New Serial Header System!/**'
      - 'PCB/**'
      - 'SYSMON65-main/**'
      - 'basic tinkering/**'
      - 'debug/**'
      - 'images/**'
      - 'sd card contents/**'
      - 'stuff thats on loader/**'
      - 'tests/**'
      - 'the video chip/**'
      - 'vasm6502/**'
      - 'xa/**'
      - 'osi_bas-master/**'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - 'New Serial Header System!/**'
      - 'PCB/**'
      - 'SYSMON65-main/**'
      - 'basic tinkering/**'
      - 'debug/**'
      - 'images/**'
      - 'sd card contents/**'
      - 'stuff thats on loader/**'
      - 'tests/**'
      - 'the video chip/**'
      - 'vasm6502/**'
      - 'xa/**'
      - 'osi_bas-master/**'
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "demo"
  demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Assemble with vasm
        run: |
          cd "19200 Baud (a demo)/"
          ./vasm6502_oldstyle -Fbin -dotdir -c02 demo.s -o "../sd card contents/folder/demo.xpl"
